log context
cognitedata/dotnet-simulator-utils pull request #120
Opened 2024-04-17 12:22 UTC by lpereiracgn

2024-04-17 14:15 UTC, abdullah-cognite approved these changes

2024-04-17 14:30 UTC, polomani commented on Cognite.Simulator.Utils/ScopedRemoteApiSink.cs
> +                        }
can we please not assign 0 and make a value nullable or smth?
defaulting things to 0 make these sort of bugs to happen in the first place

2024-04-17 14:31 UTC, polomani requested changes
make the param optional in case it is optional

2024-04-17 14:38 UTC, polomani commented on Cognite.Simulator.Utils/ScopedRemoteApiSink.cs
> +                        }
the defaulting logic happens somewhere in the library as well I assume

2024-04-23 09:13 UTC, abdullah-cognite approved these changes

2024-04-23 09:14 UTC, abdullah-cognite commented
@lpereiracgn test needs a tiny fix

2024-04-23 10:15 UTC, polomani commented
@lpereiracgn can you explain in what case we have zeros in this part of the code?

2024-04-23 10:59 UTC, abdullah-cognite commented
> @lpereiracgn can you explain in what case we have zeros in this part of the code?

in case logId was mistakenly set to an empty string by any other part of the code.

2024-04-23 11:44 UTC, polomani approved these changes
LGTM

2024-04-23 13:54 UTC, merged